name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync code to remote server
      run: |
        rsync -avz --delete \
        -e "ssh -o StrictHostKeyChecking=no" \
        ./public ubuntu@82.157.191.56:/home/ubuntu/www

    - name: Restart remote service
      run: |
        ssh -o StrictHostKeyChecking=no user@remote-server 'sudo systemctl restart your-service'
